args=commandArgs(T)
library(dplyr)
cov_1k <- read.table(paste0(args[1],"coverage/1k_interaction.txt"),sep = "\t",header=F,stringsAsFactors = F)
cov_1k$V2<-as.integer(cov_1k$V2)
colnames(cov_1k)<-c("Chr","Start","End","Value","Virus")
cov_1k<-filter(cov_1k,Virus %in% c("h","v"))
library(ggplot2)
p<-ggplot(cov_1k,aes(x=Start,y=Value,group=1,color=Virus))+geom_line()+scale_color_manual(values = c("#BEBEBE","#CD3333","#79CDCD"))+facet_wrap(~Chr,scales="free")
ggsave(filename=paste0(args[1],"R_plot/all.pdf"), plot=p, width=30, height=30, units="in")
